### ISSUE TITLE
Inverted Bunny Walking

### ISSUE THREAD

**Issue by shananas** [StripesOO7/alttp-ap-poptracker-pack#10]
After defeating Aga 1 when inverted (assuming required tools for logic) without moon pearl there are a handful of checks in logic in light world as a bunny that are not marked as in logic that are in logic.
Kakariko well chests (minus the bomb wall) since falling in activates super bunny
Kakriko Bottle Merchant since you can talk as a bunny (do not need super bunny)
Returning the Dwarf (assuming you have titans to get him form dark world) same reason as above
Purple Chest (same reason as previous two)

**Comment by StripesOO7** [comment]
Just to confirm. Is superbunny state expected to be in logic under "no-glitches"? If not. Which logic state first expects super hunny state

**Comment by shananas** [comment]
The only superbunny in logic is superbunny cave and kakariko well chests(minus the bomb wall) since dropping to those chests activates super bunny

**Comment by shananas** [comment]
Edited my previous comment a few times posting this since it's aren't notified.

**Comment by StripesOO7** [comment]
Ok i'm gonna see how i can implement this then.

**Comment by StripesOO7** [comment]
this will be "harder" to do clean then i thought. since i basiccaly have to make a rule for every door connecttion that its only doable with the respective game state just do distinct the explicit 4 locations

**Comment by StripesOO7** [comment]
I think i found a way to make this possible. I'll put it in the next release

**Comment by StripesOO7** [comment]
> The only superbunny in logic is superbunny cave and kakariko well chests(minus the bomb wall) since dropping to those chests activates super bunny
> You are not expected to receive an item (which makes sense this would be terrible and missable) to activate it.
> You are also not expected to mirror or be hit by an enemy the same frame you enter a door(I think it's the same frame might be 1 frame after still its not expected)

Is this now solved? Or are there still locations missing that should he accessible via bunny walking?

**Comment by shananas** [comment]
I havent played AP in a while but i can maybe get around to just loading the tracker in poptracker and check sometime soon hopefully

**Comment by shananas** [comment]
finally checked the tracker (not in a game just clicking the required items with inverted on) and it looks correct so ill close this issue
