### ISSUE TITLE
Key Drop: On Overworld map, in HC "Zelda's Chest" uses Big Key logic, Key Drops section does not.

### ISSUE THREAD

**Issue by TheT113** [StripesOO7/alttp-ap-poptracker-pack#7]
On the Overworld map, Zelda's Chest is green without having the Big Key, and the Key Drops field is red. This is not an issue on the individual maps.

It may be worth separating the Key Drops out to their own locations instead of together, since they have different logic.

**Comment by StripesOO7** [comment]
yeah. thats pobably a good idea for hyrule castel/castle escape
